
  singleQuote: true
  trailingComma: es5
  semi: false
  printWidth: 100
  plugins: 
    - "prettier-plugin-solidity"
  overrides: 
     -  files: "*.sol"
        options: 
          printWidth: 100
          singleQuote: true
          bracketSpacing: true
          explicitTypes: always
 
